version: "3.9"

services:
  db:
    image: postgres:15
    container_name: mro_postgres
    restart: always
    environment:
      POSTGRES_USER: mro_user
      POSTGRES_PASSWORD: mro_password
      POSTGRES_DB: mro_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
